name: demo_1robot_nav
map:
  width: 10
  height: 7
  obstacles:
    - [5, 0]
    - [5, 6]
robots:
  robot_0:
    start: [1, 1]
    goal: [8, 1]
objects: {}
max_steps: 30
render: false
centralized_rule: false
